import ReactMarkdown from 'react-markdown';
import { cn } from '../lib/utils';
import { Brain, ExternalLink } from 'lucide-react';

interface ReportViewerProps {
  content: string;
  className?: string;
}

export function ReportViewer({ content, className }: ReportViewerProps) {
  if (!content) {
    return (
      <div className={cn("flex flex-col items-center justify-center p-12 text-center border-2 border-dashed border-gray-200 rounded-xl bg-gray-50", className)}>
        <Brain className="w-12 h-12 text-gray-300 mb-4" />
        <h3 className="text-lg font-medium text-gray-900">No Analysis Yet</h3>
        <p className="text-sm text-gray-500 max-w-sm mt-1">
          Enter your business idea and click "Analyze Idea" to generate your comprehensive legal and business report.
        </p>
      </div>
    );
  }

  return (
    <div className={cn("bg-white border rounded-xl shadow-sm overflow-hidden", className)}>
      <div className="px-6 py-4 border-b bg-gray-50 flex items-center justify-between sticky top-0 z-10">
        <h2 className="font-semibold text-gray-800 flex items-center gap-2">
          <Brain className="w-5 h-5 text-indigo-600" />
          Intelligence Report
        </h2>
        <button 
          className="text-xs text-gray-500 hover:text-indigo-600 flex items-center gap-1 transition-colors"
          onClick={() => window.print()}
        >
          <ExternalLink className="w-3 h-3" />
          Export / Print
        </button>
      </div>
      
      <div className="p-6 md:p-8 markdown-body prose prose-indigo max-w-none prose-headings:font-semibold prose-h1:text-2xl prose-h2:text-xl prose-h3:text-lg">
        <ReactMarkdown>{content}</ReactMarkdown>
      </div>
      
      <div className="p-4 bg-yellow-50 border-t border-yellow-100 text-xs text-yellow-800">
        <strong>Disclaimer:</strong> This report is generated by an AI agent and is intended for informational and planning purposes only. It does not constitute formal legal advice. Always consult with a qualified attorney for legal compliance.
      </div>
    </div>
  );
}
